#!/bin/bash
#
# apm - Shortcut to launch APM Tracker in interactive mode
#

if [ "$EUID" -ne 0 ]; then
    echo "This program requires root permissions to access input devices."
    exec sudo /usr/local/bin/apm_tracker
else
    exec /usr/local/bin/apm_tracker
fi